### ISSUE TITLE
GPU显存不足

### ISSUE THREAD

**Issue by lishijie15** [thuml/TimesNet#2]
同学你好，在运行时碰到了以下的问题
RuntimeError: CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 23.99 GiB total capacity; 22.60 GiB already allocated; 0 bytes free; 22.75 GiB reserved in total by PyTorch)
在运行timesnet前我确定显存已经清理干净了，也尝试调小batch_size，但是仍然超显存，你论文中的显卡也是24g的，我想问问你是否有遇到这样的问题，你是怎样处理的呢？

**Comment by wuhaixu2016** [comment]
您好，我也是24GB显存的机器，而且timesnet所有的实验都不会超过20GB，具体是跑哪个script出问题的呢？

**Comment by lishijie15** [comment]
> 您好，运行参数为--task_name long_term_forecast --is_training 1 --model_id train --model TimesNet --data ETTh2

![image](https://user-images.githubusercontent.com/38575418/221806672-b088ae0f-a77a-48ea-b67f-3543d92eeb86.png)

**Comment by htg17** [comment]
似乎您没有设置d_model和d_ff，run.py里面的默认值比较大。建议使用我们提供的script跑，具体为：
`sh ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh2.sh`

**Comment by lishijie15** [comment]
好的，已经解决了，谢谢
